# .github/workflows/keep-alive.yml
name: Mantener Upstash Alive

# Ejecutar cada día a las 03:00 UTC (las 00:00 en Argentina)
on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  ping_upstash:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar PING a Upstash
        run: |
          curl -s -X POST ${{ secrets.UPSTASH_REST_URL }}/ \
            -H "Authorization: Bearer ${{ secrets.UPSTASH_REST_TOKEN }}" \
            -d '["PING"]' \
            -o /dev/null \
            && echo "✅ PONG recibido" \
            || echo "❌ Error al hacer PING"
